- WinNUT_V2/WinNUT_GUI/Shutdown_Gui.vb
- WinNUT_V2/WinNUT_GUI/WinNUT.vb
Clone of @g-cranston 's pull request here: https://github.com/gawindx/WinNUT-Client/pull/125
Related: Issue https://github.com/nutdotnet/WinNUT-Client/issues/2
**Original text:**
https://github.com/gawindx/WinNUT-Client/issues/89
Allowing Hibernate/Suspend in Windows 10.
https://github.com/gawindx/WinNUT-Client/issues/123
Clears the timer so that it doesn't repeat trying to shutdown after resuming the system.
> Windows 10 Hibernate & Clear Shutdown Timer (redo)

- WinNUT_V2/WinNUT-Client_Common/Common_Enums.vb
- WinNUT_V2/WinNUT-Client_Common/Logger.vb
- WinNUT_V2/WinNUT-Client_Common/Nut_Socket.vb
- WinNUT_V2/WinNUT-Client_Common/UPS_Device.vb
- WinNUT_V2/WinNUT-Client_Common/WinNUT_Globals.vb
- WinNUT_V2/WinNUT_GUI/About_Gui.vb
- WinNUT_V2/WinNUT_GUI/ApplicationEvents.vb
- WinNUT_V2/WinNUT_GUI/List_Var_Gui.vb
- WinNUT_V2/WinNUT_GUI/Pref_Gui.vb
- WinNUT_V2/WinNUT_GUI/Shutdown_Gui.vb
- WinNUT_V2/WinNUT_GUI/Update_Gui.vb
- WinNUT_V2/WinNUT_GUI/WinNUT.vb
Make both cosmetic and functional improvements to the way logging works in WinNUT. Notably:
- Rename variables and functions so that they better communicate their purpose
- Move variables within classes for better OOP design, where appropriate
- Document some functions and behaviors
- Move log files to their own subdirectory, and store them next to the executable when debugging.
- Modified how logging controls behave in the Prefs GUI: more simple from a code standpoint, and verified functionality
- Create more informative log entries
Will hopefully benefit #4 and others.
> Logging Improvements

- WinNUT_V2/SharedAssemblyInfo.vb
- WinNUT_V2/WinNUT-Client_Common/Logger.vb
- WinNUT_V2/WinNUT-Client_Common/WinNUT_Globals.vb
- WinNUT_V2/WinNUT_GUI/App.config
- WinNUT_V2/WinNUT_GUI/ApplicationEvents.vb
- WinNUT_V2/WinNUT_GUI/My Project/AssemblyInfo.vb
- WinNUT_V2/WinNUT_GUI/Pref_Gui.vb
- WinNUT_V2/WinNUT_GUI/Update_Gui.vb
- WinNUT_V2/WinNUT_GUI/WinNUT-client.vbproj
- WinNUT_V2/WinNUT_GUI/WinNUT.vb
- Lots of code cleanup throughout the project, simplifying references and removing imports.
- Logger tweaks; max events stored in buffer is 4x increased
- Against my earlier quest for Object-Oriented Programming, I've moved the Logger object back into Globals.
- The Globals are now initialized in the App startup method rather than the Form's, this way they should be more "global".
- Tweaked the crash report dialog to be slightly more predictable and user-friendly (in case copy to clipboard fails)
- Fixed crash in Update_Gui due to missing variable
> Additional logging improvements and cleanup

- WinNUT_V2/WinNUT-Client_Common/UPS_Device.vb
- WinNUT_V2/WinNUT-Client_Common/WinNUT_Params.vb
- WinNUT_V2/WinNUT_GUI/About_Gui.vb
- WinNUT_V2/WinNUT_GUI/List_Var_Gui.vb
- WinNUT_V2/WinNUT_GUI/Pref_Gui.vb
- WinNUT_V2/WinNUT_GUI/WinNUT.vb
- Handle disconnections better by separating and centralizing subroutines
- Small modifications to the Pref_Gui to make the main form more responsive to modifications
- Fix two NullReferenceExceptions, in About_Gui and List_Var_Gui
- General code cleanup throughout
> Better disconnection handling in main form

- WinNUT_V2/WinNUT-Client_Common/Common_Classes.vb
- WinNUT_V2/WinNUT-Client_Common/Nut_Socket.vb
- WinNUT_V2/WinNUT-Client_Common/UPS_Device.vb
- WinNUT_V2/WinNUT_GUI/List_Var_Gui.vb
- WinNUT_V2/WinNUT_GUI/WinNUT.vb
- New Nut_Exception constructor to allow specifying NUTResponse instead of _Exception_Value
- Shifted some responsibility of error handling out of Socket class and into UPS class. These are some major changes and need testing.
- Merged Create_Socket code into Connect code
- Renamed and then commented-out IsKnownUPS function. Feels like this should be a part of the UPS class, but regardless, we'll know if there's an invalid UPS the moment a command is run for one.
- Simplified & renamed Query_Desc function
- Added a few events to the UPS class for informing any listeners of issues
- UPS no longer handles socket errors, and instead passively notifies listeners about one
- GetUPSVar supports DATA-STALE errors and will retry 3 times to get the data, and then take the default value and raise …
> Large changes to Socket/UPS, DATA-STALE error handling

- WinNUT_V2/WinNUT-Client/Shutdown_Gui.vb
- WinNUT_V2/WinNUT-Client/WinNUT.vb
- WinNUT_V2/WinNUT-Client_Common/Common_Classes.vb
- WinNUT_V2/WinNUT-Client_Common/Common_Enums.vb
- WinNUT_V2/WinNUT-Client_Common/Nut_Socket.vb
- WinNUT_V2/WinNUT-Client_Common/UPS_Device.vb
- WinNUT_V2/WinNUT-Client_Common/WinNUT_Globals.vb
It looks like the stop action system was disabled during the client library changes. I've reactivated it.
I've also redone how UPS statuses are updated and processed, in the hopes of making program execution more efficient and bug-Closes #27
> Re-activate stop actions system and status updates overhaul

- Translation/de-DE/de-DE.csv
I made some small updates to the german translation and changed the german word Batterie to Akku as i believe it to be more fitting.
There also some "To Validate" lines, that i would consider good, however i do not know your procedure for validating, so i did not touch them, however i could validate some of them, as they make perfect sense to me
> Small updates to german Translation

- WinNUT_V2/WinNUT-Client/Pref_Gui.vb
- WinNUT_V2/WinNUT-Client/WinNUT.vb
The Interval/Delay value has been incorrectly set in older versions to 0, which causes an ArgumentOutOfRange exception upon connecting the UPS. Make sure this value is corrected when Prefs are updated, and make sure the Prefs form validates the field.
Closes #35.
> Correct Interval/Delay value

- WinNUT_V2/Setup/Setup.vdproj
Excluding unneeded dependencies that had been added from the toast notifications nuget package. Also removing the program shortcut from the program files folder, and adding a shortcut to the README in the start menu folder. Bumping to version 8331.
> Installer dependency cleanup

- WinNUT_V2/Setup/Setup.vdproj
- WinNUT_V2/WinNUT-Client_Common/WinNUT_Globals.vb
Fixed the log file being created at the root of the system drive. It now generates correctly in the Roaming appdata folder when running a standard release build (locally when debugging.)
Closes #43
> Logging fixes

- WinNUT_V2/Setup/Setup.vdproj
- WinNUT_V2/WinNUT-Client/WinNUT.vb
Added some missing manifest files to the installer so the Windows version is detected correctly now. Also added some additional debugging information when toast notifications are disabled.
Closes #44
> Fix incorrect windows version detection

- WinNUT_V2/WinNUT-Client/List_Var_Gui.vb
- WinNUT_V2/WinNUT-Client/WinNUT.vb
- WinNUT_V2/WinNUT-Client_Common/Nut_Socket.vb
- WinNUT_V2/WinNUT-Client_Common/UPS_Device.vb
List_Var_Gui has been throwing an error, because the list query method stopped parsing a response before it was complete, resulting in multiple queries running at once and creating an exception.
Closes #45
> Fix List_Var_Gui error

- WinNUT_V2/WinNUT-Client/WinNUT.vb
Respect the Follow_FSD setting when a FSD flag is set.
Closes #55
> Respect Follow FSD setting

- WinNUT_V2/WinNUT-Client_Common/Logger.vb
- WinNUT_V2/WinNUT-Client_Common/WinNUT_Globals.vb
Judging from my Debugging output folder, it looks like generating the application's data directory has been broken since after November 11. Not quite sure what commit did it, but here's a summary of what's in this PR:
- General reorganization of the `WinNUT_Globals` Module.
- Altered some constants to be more consistent, made shortcut properties and general static strings defined within the module itself.
- As a result, the Init_Globals function is one line.
- This calls the new GetAppDirectory function. It returns the best directory for storing application data (currently Logs only), starting with the specified string as the directory wanted. If that fails (i.e debug build in a read-only directory, or appdata directory is not available for some reason) then we'll use the user's default …
> Attempting to finally solve data directory oddities

- WinNUT_V2/WinNUT-Client/WinNUT.vb
- WinNUT_V2/WinNUT-Client_Common/Nut_Socket.vb
Closes #63 
A few issues have been brought up:
- The WinNUT UI is left in an inconsistent state when the connection to a NUT server is unexpectedly lost.
- The `streamInUse` latch variable was left locked when the connection was broken, resulting in future queries failing.
> Improve connection loss handling

- WinNUT_V2/WinNUT-Client_Common/Common_Enums.vb
The existing state detection logic relies on bitwise operations to compare old and new state and to extract the changed state flags. However it's fundamentally broken due to UPS_States enum not using the power of 2 values. Bitwise logic produces invalid states change set because of that.
I discovered it while I was trying to make this client follow FSD signal from the server. But it never detects the change for FSD state. The only case when it starts the shutdown procedure is if you connect to the server which is already in FSD state.
> Define UPS_States values as pow of 2 to fix state change detection

- WinNUT_V2/WinNUT-Client_Common/WinNUT_Globals.vb
Not much to describe here. A superfluous bracket was causing the Release build to crash.
> Fix release build

- WinNUT_V2/WinNUT-Client/ApplicationEvents.vb
- WinNUT_V2/WinNUT-Client/WinNUT-client.vbproj
- WinNUT_V2/WinNUT-Client/WinNUT.vb
- WinNUT_V2/WinNUT-Client_Common/Nut_Socket.vb
- WinNUT_V2/WinNUT-Client_Common/UPS_Device.vb
- WinNUT_V2/WinNUT-Client_Common/WinNUT_Globals.vb
Per #79 and #80:
Another issue like #49 , some thrown exceptions aren't being caught by the bug report generator. More work is needed in that area.
In addition, ~~certain~~ Synology NUT servers allow a client to LOGIN successfully, but will then reply ACCESS-DENIED to a LOGOUT command. I don't think this should be happening, but regardless, we're not catching a protocol exception and allowing it to crash the program. Need to make sure we're handling protocol exceptions appropriately.
- More reorganization in WinNUT_Globals.vb. Renaming some variables for clarity.
- Updated dependencies
- Refactor error report generation. Attempts to account for more error conditions and ensure a report can be generated.
- Various improvements to protocol code, focusing on the Login subroutine.
- …
> Error Reporting & Exception Catching Refactor

- WinNUT_V2/WinNUT-Client/Update_Gui.vb
Prevent crashing by wrapping `Convert.ToDateTime` in Try-Catch block (default operation will continue with update), and in the future, store dates in a standard format for parsing.
Closes #78
> Fix FormatException in Update_Gui

- WinNUT_V2/WinNUT-Client/WinNUT.vb
When Minimize and/or Close to tray is enabled, any calls to Application.Exit are cancelled and WinNUT instead simply hides its self as if it were being minimized/closed to the tray. The application now checks if the user meant to minimize/close it to the tray, otherwise it will exit normally.
Closes #105
> Fix unable to exit with tray closing functionality

- WinNUT_V2/WinNUT-Client/WinNUT.vb
I had disabled the auto-retry functionality at start because the program hangs as it tries to connect. We'll need to address multithreaded app functionality to truly fix this. In the mean time, WinNUT will now try to automatically reconnect at start when connection issues are encountered.
Closes #104
> Re-enable retry connection on first start
